// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tofnyrjfvloncyqhixlc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvZm55cmpmdmxvbmN5cWhpeGxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NTg4ODcsImV4cCI6MjA2ODIzNDg4N30.eD6e043Y-2enIGJMhhCRe2yYMQup6BlVvCjUusGALms";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});